// <auto-generated />
using System;
using FinoBackend.Commons.Enums;
using FinoBackend.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace fino_backend.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20250911065556_Initial")]
    partial class Initial
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.0-preview.7.25380.108")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.HasPostgresEnum(modelBuilder, "file_category", new[] { "bank_statement", "delivery_receipt" });
            NpgsqlModelBuilderExtensions.HasPostgresEnum(modelBuilder, "file_extension", new[] { "jpg", "pdf", "png", "tiff", "xlsx" });
            NpgsqlModelBuilderExtensions.HasPostgresEnum(modelBuilder, "global_role", new[] { "developer", "super_admin", "user" });
            NpgsqlModelBuilderExtensions.HasPostgresEnum(modelBuilder, "owner_type", new[] { "anonymous", "authenticated_user" });
            NpgsqlModelBuilderExtensions.HasPostgresEnum(modelBuilder, "queue_type", new[] { "bank_statement_conversion", "delivery_receipt_conversion", "public_bank_statement_conversion" });
            NpgsqlModelBuilderExtensions.HasPostgresEnum(modelBuilder, "tenant_approval_status", new[] { "approved", "pending", "rejected" });
            NpgsqlModelBuilderExtensions.HasPostgresEnum(modelBuilder, "tenant_role", new[] { "admin", "member" });
            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("FinoBackend.Models.ConversionJob", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("ErrorMessage")
                        .HasColumnType("text")
                        .HasColumnName("error_message");

                    b.Property<DateTime?>("FinishedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("finished_at");

                    b.Property<DateTime?>("StartedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("started_at");

                    b.Property<int>("Status")
                        .HasColumnType("integer")
                        .HasColumnName("status");

                    b.Property<Guid?>("TenantFileId")
                        .HasColumnType("uuid")
                        .HasColumnName("tenant_file_id");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<Guid?>("UploadedFileId")
                        .HasColumnType("uuid")
                        .HasColumnName("uploaded_file_id");

                    b.HasKey("Id")
                        .HasName("pk_conversion_jobs");

                    b.HasIndex("TenantFileId")
                        .HasDatabaseName("ix_conversion_jobs_tenant_file_id");

                    b.HasIndex("UploadedFileId")
                        .HasDatabaseName("ix_conversion_jobs_uploaded_file_id");

                    b.ToTable("conversion_jobs", (string)null);
                });

            modelBuilder.Entity("FinoBackend.Models.Tenant", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("CompanyName")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("company_name");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Subdomain")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("subdomain");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id")
                        .HasName("pk_tenants");

                    b.HasIndex("CompanyName")
                        .IsUnique()
                        .HasDatabaseName("ix_tenants_company_name");

                    b.HasIndex("Subdomain")
                        .IsUnique()
                        .HasDatabaseName("ix_tenants_subdomain");

                    b.ToTable("tenants", (string)null);
                });

            modelBuilder.Entity("FinoBackend.Models.TenantFile", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<FileExtension>("FileExtension")
                        .HasColumnType("file_extension")
                        .HasColumnName("file_extension");

                    b.Property<string>("FileKey")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("file_key");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid")
                        .HasColumnName("tenant_id");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id")
                        .HasName("pk_tenant_files");

                    b.HasIndex("TenantId")
                        .HasDatabaseName("ix_tenant_files_tenant_id");

                    b.ToTable("tenant_files", (string)null);
                });

            modelBuilder.Entity("FinoBackend.Models.UploadedFile", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<FileCategory>("Category")
                        .HasColumnType("file_category")
                        .HasColumnName("category");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<FileExtension>("FileExtension")
                        .HasColumnType("file_extension")
                        .HasColumnName("file_extension");

                    b.Property<string>("OriginalFileName")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("original_file_name");

                    b.Property<string>("OutputFileKey")
                        .HasColumnType("text")
                        .HasColumnName("output_file_key");

                    b.Property<OwnerType>("OwnerType")
                        .HasColumnType("owner_type")
                        .HasColumnName("owner_type");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<string>("UploadedFileKey")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("uploaded_file_key");

                    b.Property<Guid?>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.HasKey("Id")
                        .HasName("pk_uploaded_files");

                    b.ToTable("uploaded_files", (string)null);
                });

            modelBuilder.Entity("FinoBackend.Models.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("email");

                    b.Property<GlobalRole>("GlobalRole")
                        .HasColumnType("global_role")
                        .HasColumnName("global_role");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.Property<TenantApprovalStatus?>("TenantApprovalStatus")
                        .HasColumnType("tenant_approval_status")
                        .HasColumnName("tenant_approval_status");

                    b.Property<Guid?>("TenantId")
                        .HasColumnType("uuid")
                        .HasColumnName("tenant_id");

                    b.Property<TenantRole?>("TenantRole")
                        .HasColumnType("tenant_role")
                        .HasColumnName("tenant_role");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id")
                        .HasName("pk_users");

                    b.HasIndex("TenantId")
                        .HasDatabaseName("ix_users_tenant_id");

                    b.ToTable("users", (string)null);
                });

            modelBuilder.Entity("FinoBackend.Models.ConversionJob", b =>
                {
                    b.HasOne("FinoBackend.Models.TenantFile", "TenantFile")
                        .WithMany("ConversionJobs")
                        .HasForeignKey("TenantFileId")
                        .HasConstraintName("fk_conversion_jobs_tenant_files_tenant_file_id");

                    b.HasOne("FinoBackend.Models.UploadedFile", "UploadedFile")
                        .WithMany("ConversionJobs")
                        .HasForeignKey("UploadedFileId")
                        .HasConstraintName("fk_conversion_jobs_uploaded_files_uploaded_file_id");

                    b.Navigation("TenantFile");

                    b.Navigation("UploadedFile");
                });

            modelBuilder.Entity("FinoBackend.Models.TenantFile", b =>
                {
                    b.HasOne("FinoBackend.Models.Tenant", "Tenant")
                        .WithMany("SharedFiles")
                        .HasForeignKey("TenantId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_tenant_files_tenants_tenant_id");

                    b.Navigation("Tenant");
                });

            modelBuilder.Entity("FinoBackend.Models.User", b =>
                {
                    b.HasOne("FinoBackend.Models.Tenant", "Tenant")
                        .WithMany("Users")
                        .HasForeignKey("TenantId")
                        .HasConstraintName("fk_users_tenants_tenant_id");

                    b.Navigation("Tenant");
                });

            modelBuilder.Entity("FinoBackend.Models.Tenant", b =>
                {
                    b.Navigation("SharedFiles");

                    b.Navigation("Users");
                });

            modelBuilder.Entity("FinoBackend.Models.TenantFile", b =>
                {
                    b.Navigation("ConversionJobs");
                });

            modelBuilder.Entity("FinoBackend.Models.UploadedFile", b =>
                {
                    b.Navigation("ConversionJobs");
                });
#pragma warning restore 612, 618
        }
    }
}
